import {Lato} from "next/font/google";
import "./globals.css";
import Header from "../../components/Header";
import Footer from "@/components/Footer";
import {FC, ReactNode} from "react";
import "../../i18n/i18n";
import duration from "dayjs/plugin/duration"; // ES 2015
import relativeTime from "dayjs/plugin/relativeTime";
import "dayjs/locale/en";
import "dayjs/locale/uk";
import dayjs from "dayjs";

dayjs.extend(duration);
dayjs.extend(relativeTime);

interface RootLayoutProps {
    children: ReactNode;
    params: { locale: string }
}

const lato = Lato({
    subsets: ["latin"],
    weight: ["400", "700"],
    style: ["normal", "italic"],
    display: "swap",
});

// TODO: convert to metadata with locale (getMetadata, next-intl)
export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const RootLayout: FC<RootLayoutProps> = async ({children, params: {locale}}) =>
    (
        <html lang={locale}>
        <body className={lato.className}>
        <Header></Header>
        <div>{children}</div>
        <Footer></Footer>
        </body>
        </html>
    );
export default RootLayout
